# -*- coding: utf-8 -*-
"""Exercicios Estruturas de Repeticao While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHSk2KI2-jRLWrxq1FHsu62RwyBb9KkE

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

nota = int(input("informe uma nota entre 0 e 10 : "))
while  nota < 0 or nota > 10:
  print("Nota invalida, informe uma nota entre 0 e 10")
  nota = int(input("informe uma nota entre 0 e 10 :"))

"""2. Faça um programa que calcule o mostre a média aritmética de N notas.

"""

acum = 0
total = 0
n=int(input("Informe a quantidade de notas: "))
while acum <= n:
  total += float(input("Informe a proxima nota: "))
  acum +=1
print(f"A média das notas é de: {(total/n)} ")

"""3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.

"""

nome=str(input("Usuario: "))
senha = str (input("Senha: "))
while nome==senha :
  print("A senha não pode ser igual ao nome")
  nome=str(input("Usuario: "))
  senha = str (input("Senha: "))

"""4. Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.


"""

salario=float(input("Informe o salário a ser calculado: "))
corr=0.015
ano = 1996
while ano < 2024:
  print(f"Salário em {ano} = R$ {salario+(salario*corr)}, correção de {corr*100}% em relação ao ano anterior")
  ano += 1
  corr*=2

"""5. Faça um programa que leia e valide as seguintes informações:
* Nome: maior que 3 caracteres;
* Idade: entre 0 e 150;
* Salário: maior que zero;
* Sexo: 'f' ou 'm';
* Estado Civil: 's', 'c', 'v', 'd';

"""

nome=str(input("Informe o nome: "))
while len(nome)<=3:
  nome=input("Nome inválido, necessita ter pelo menos 3 caracteres.Informe nome válido: ")
idade = int(input("Informe a idade: "))
while idade< 0 or idade>150:
  idade = input("Informe uma idade válida entre 0 e 150: ")
genero = str(input("Informe o gênero, f para feminino ou m para masculino: ")).lower()
while genero != 'f' and genero!= 'm':
  genero = input("Informe um gênero válido, f ou m: ")
estado = str(input("Informe estado civil: s para solteiro(a), c para casado(a, v para viuvo(a), d para divorciado(a)")).lower()
while estado !=  's' and 'c' and 'v' and 'd':
  estado = (input ("Entrada inválida, digite s para solteiro(a), c para casado(a, v para viuvo(a), d para divorciado(a): ")).lower()

"""6. Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.

"""

pop_a=80000
pop_b=200000
ano= 0
while pop_a <= pop_b:
  pop_a=pop_a+(pop_a*0.03)
  pop_b=pop_b+(pop_b*0.015)
  ano+=1
print(f"Tempo para população A superar a população B: {ano} anos\n População A terá {pop_a:.2f} habitantes\n População B terá {pop_b:.2f} habitantes")

"""7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

numero=int(input("Informe o número a ter seu fatorial calculado"))
resultado = numero
while 1 < numero:
  resultado *=  (numero-1)
  numero -=1
print(f"{resultado}")

"""8. Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

acum = 0
sum = 0
num = 1
while num !=0:
  num = float(input("Informe o número para entrar na média "))
  sum = sum + num
  acum = acum + 1
acum = acum -1
print(f"A média dos números informados é = {sum/acum}")

"""9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
programa capaz de gerar a série até o n−ésimo termo.
"""

termo = int(input("Informe o termo a ser calculado: "))
if termo == 1:
  print("1")
elif (termo ==2):
  print("1,\n1,")
else:
  cont = 1
  x1, x2 = 1, 1
  while cont <= termo:
    print(f"O {cont}º termo: {x1},")
    temp = x1 + x2
    x1=x2
    x2=temp
    cont += 1

#1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987,

"""10. O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
* O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
* O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
* A saída deve ser conforme o exemplo abaixo:
* Lojas Tabajara
* Produto 1: R$ 2.20
* Produto 2: R$ 5.80
* Produto 3: R$ 0
* Total: R$ 9.00
* Dinheiro: R$ 20.00
* Troco: R$ 11.00
"""

print("Lojas tabajara")
ttl = 0
cont = 1
vlr= float
while vlr != 0:
  vlr= float(input(f"Produto {cont}: R$ "))
  cont+=1
  ttl=ttl+vlr
print(f"Total: R$ {ttl}")
money = float(input("Dinheiro: R$ "))
print(f"Troco: R$ {money-ttl}")

"""11. O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço

*  Cachorro Quente 100 R$ 1,20  
*  Bauru Simples 101 R$ 1,30  
*  Bauru com ovo 102 R$ 1,50  
*  Hambúrguer 103 R$ 1,20
*  Cheeseburguer 104 R$ 1,30
*  Refrigerante 105 R$ 1,00

Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

item_count = 0
ttl = 0
saida = str
while saida != 'n':
  item = float(input("Informe o código do ítem: "))
  if item == 100:
    print ("Cachorro quente : R$ 1.20 ")
    qtd_100 = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_100 } x 1.20 = R$ {qtd_100*1.20} ")
    ttl = ttl + (qtd_100 * 1.20)
  elif item == 101:
    print ("Baruru Simples : R$ 1.30 ")
    qtd_101 = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_101 } x 1.30 = R$ {qtd_101*1.30} ")
    ttl = ttl + (qtd_101 * 1.30)
  elif item == 102:
    print ("Baruru com ovo : R$ 1.50 ")
    qtd_102 = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_102 } x 1.50 = R$ {qtd_102*1.50} ")
    ttl = ttl + (qtd_102 * 1.50)
  elif item == 103 :
    print ("Hambúrguer : R$ 1.20 ")
    qtd_103  = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_103  } x 1.20 = R$ {qtd_103 * 1.20 } ")
    ttl = ttl + (qtd_103  * 1.20)
  elif item == 104 :
    print ("Cheeseburguer : R$ 1.30 ")
    qtd_104  = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_104  } x 1.20 = R$ {qtd_104*1.30 } ")
    ttl = ttl + (qtd_104 * 1.30)
  elif item == 105 :
    print ("Refrigerante : R$ 1.00 ")
    qtd_105  = int(input("informe a quantidade: "))
    print(f"Subtotal: { qtd_105  } x 1.20 = R$ {qtd_105*1.20 } ")
    ttl = ttl + (qtd_105 * 1.00)
  else:
    print("Opção inválida")
  saida = str(input("Deseja algo mais? s/n ")).lower()
print(f"Total: R$ {ttl}")

"""12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados
por meio de código.
Os códigos utilizados são:
* 1, 2, 3, 4 - Votos para os respectivos candidatos
* (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
* 5 - Voto Nulo
* 6 - Voto em Branco.

Faça um programa que calcule e mostre:
* O total de votos para cada candidato;
* O total de votos nulos;
* O total de votos em branco;
* A percentagem de votos nulos sobre o total de votos;
* A percentagem de votos em branco sobre o total de votos.
Para finalizar o conjunto de votos tem-se o valor zero.
"""



tt_1,tt_2,tt_3,tt_4,tt_n,tt_b, tt_fin = 0,0,0,0,0,0,0
while saida !='0':
  voto=int(input("Escolha a opção desejada: \n1-José\n2-João\n3-Maria\n4-Marta\n5-Nulo\n6-Branco\n "))
  if (voto == 1):
    tt_1 += 1
    tt_fin +=1
  elif(voto==2):
    tt_2 += 1
    tt_fin +=1
  elif(voto==3):
    tt_3 += 1
    tt_fin +=1
  elif(voto==4):
    tt_4 += 1
    tt_fin +=1
  elif(voto==5):
    tt_n += 1
    tt_fin +=1
  elif(voto==6):
    tt_b += 1
    tt_fin +=1
  else: print("Opção inválida")
  saida=str(input("Digite 0 para encerrar a votação, ou outro valor para continuar: "))
saida = 1
#camp=(tt_1,tt_2,tt_3,tt_4).index(max((tt_1,tt_2,tt_3,tt_4)))
#if camp == (0):
  #print("Vencedor foi Jos")
print(f"Resultado final da votação: ")
print(f"José: {tt_1} votos")
print(f"João: {tt_2} votos")
print(f"Maria: {tt_3} votos")
print(f"Marta: {tt_4} votos")
if(tt_n != 0):
  print(f"Percentual de votos nulos: {(tt_n/tt_fin)*100} % dos votos totais")
else:
  print("Não houveram votos nulos")
if(tt_b != 0):
  print(f"Percentual de votos Brancos: {(tt_btt_fin/tt_fin)*100} % dos votos totais")
else:
  print("Não houveram votos em branco")

